apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepecoscan-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepecoscan-frontend
  template:
    metadata:
      labels:
        app: deepecoscan-frontend
    spec:
      containers:
      - name: frontend
        image: hbastian/deepecoscan-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: deepecoscan-frontend-service
spec:
  selector:
    app: deepecoscan-frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
