---
#
# Traefik Forward Auth Deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-forward-auth
  labels:
    app: traefik-forward-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-forward-auth
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: traefik-forward-auth
    spec:
      # hostAliases:
      # - ip: "10.131.254.190"
      #   hostnames:
      #   - "jupyterhub.cs.mtsu.edu"
      terminationGracePeriodSeconds: 60
      containers:
      # This image will work with many different providers, including GitHub.
      # See: https://github.com/thomseddon/traefik-forward-auth
      # However, I have created a custom image that works with our JupyterHub OAuth2
      # setup that does not require email access.
      # - image: jphillips/traefik-forward-auth:2
      # The image here is compatible with github (but adds @phillips-lab.org to each username)
      - image: jlphillips/traefik-forward-auth:phillips-lab
        name: traefik-forward-auth
        ports:
        - containerPort: 4181
          protocol: TCP
        env:
        # Note that you need to configure JHub with an unlisted service
        # that matches the CLIENT_ID and CLIENT_SECRET, and URL_PATH
        # for the callback URL (automatic).
        # - name: DOMAIN
        #   value: "raziel.cs.mtsu.edu"
        - name: LOG_LEVEL
          value: debug
        # INSECURE_COOKIE is required unless using https entrypoint
        - name: INSECURE_COOKIE
          value: "false"
        - name: SECRET
          value: "a-random-32-hex-character-string-should-go-here"
        - name: DEFAULT_PROVIDER
          value: "generic-oauth"
        - name: PROVIDERS_GENERIC_OAUTH_SCOPE
          value: "identify"
        - name: PROVIDERS_GENERIC_OAUTH_AUTH_URL
          value: "https://jupyterhub.cs.mtsu.edu/phillips-lab/hub/api/oauth2/authorize"
        - name: PROVIDERS_GENERIC_OAUTH_TOKEN_URL
          value: "https://jupyterhub.cs.mtsu.edu/phillips-lab/hub/api/oauth2/token"
        - name: PROVIDERS_GENERIC_OAUTH_USER_URL
          value: "https://jupyterhub.cs.mtsu.edu/phillips-lab/hub/api/user"
        - name: PROVIDERS_GENERIC_OAUTH_CLIENT_ID
          value: "service-open-webui-oauth2"
        - name: PROVIDERS_GENERIC_OAUTH_CLIENT_SECRET
          value: "a-32-hex-character-client-secret-goes-here-must-match-jupyterhub"
        - name: URL_PATH
          value: "/_oauth"
---
#
# Auth Service
#
apiVersion: v1
kind: Service
metadata:
  name: traefik-forward-auth
  labels:
    app: traefik-forward-auth
spec:
  type: ClusterIP
  selector:
    app: traefik-forward-auth
  ports:
  - name: auth-http
    port: 4181
    targetPort: 4181
---
#
# Auth Middleware
#
# Example ONLY: Needs to be made in another
# namespace and # attached to an IngressRoute
#
# apiVersion: traefik.io/v1alpha1
# kind: Middleware
# metadata:
#   name: traefik-forward-auth
# spec:
#   forwardAuth:
#     address: http://traefik-forward-auth.xxxx.svc.cluster.local:4181
#     authResponseHeaders:
#       - X-Forwarded-User

