apiVersion: v1
data:
  DO_SPACES_BUCKET: ZGVlcGVjb3NjYW4tZGF0YQ==
  DO_SPACES_ENDPOINT: aHR0cHM6Ly9ueWMzLmRpZ2l0YWxvY2VhbnNwYWNlcy5jb20=
  DO_SPACES_KEY: RE84MDFYQjJXRlJVVlFISEFKNFk=
  DO_SPACES_REGION: dXMtZWFzdC0x
  DO_SPACES_SECRET: WnRVM2RwNUVaRG8xckxFcWIxM2F5cDZ5VEdrNFFKUGtpSzFxOU9ObTI1RQ==
  MONGO_URI: bW9uZ29kYitzcnY6Ly9oYjRlOldrJTVFUWtHU01lOUJmJTI1RUBkZWVwZWNvc2Nhbi5rYXl0bjY2Lm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1EZWVwRWNvU2Nhbg==
kind: Secret
metadata:
  name: deepecoscan-secrets
