apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepecoscan-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepecoscan-backend
  template:
    metadata:
      labels:
        app: deepecoscan-backend
    spec:
      containers:
      - name: deepecoscan-backend
        image: hbastian/deepecoscan-backend:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /app/temp_uploads
          name: upload-storage
      volumes:
      - name: upload-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: deepecoscan-backend-service
spec:
  selector:
    app: deepecoscan-backend
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
