apiVersion: v1
kind: Service
metadata:
  name: deepecoscan-frontend-service
spec:
  selector:
    app: deepecoscan-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
