---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefik-forward-auth-secrets
  namespace: default
spec:
  encryptedData:
    PROVIDERS_GENERIC_OAUTH_CLIENT_SECRET: AgAkKw6f0MM/G1/GdnYw6AMxExuwz5u7BfkPUprMuxbWW1ZR7z7EnkUcAZcBlPtDZ48PVcOiGegTzW+NgmrJC+tUVhihSbDAn83zmrd4/xT9Styw8AIgaFmdMlbQkecQij0W46lJAHP5XgSo43MbhW0N3kLC3E1S+RhO7Cwd7RBwKZfLSimds1ZmXyXwD+FJQB3805dpTBItjUM3ZCvYZWOiLSh7A3oZZO5AlFPUKhA+UqtDvPmOK00+IFGZgJLzyBApjWkUr3eZ624t7y2WSGhB8OaXPYjApW7EpUhXZgxp5CdtuRfOIIOktSNskOWtQeyxQHEejoBWkFgokjMW5yRBDBX/g2LyaDmxQIKNCa+iZMsSTsCu83+/iJZUnL45vC+xyUiNhwzTkB+XvqilnHh5WlesIgh0L/moFsOunVyB9SpxUc23wmkpjj+510Rn0d/GgMhOMaOu6uqtgfXSzOHdNeA5s9hUPt1J5A3brxQNxSowjH/cKwTZeUMfvjfoKfT3eMohjqoFdQETyysYjfMkMfJuhkeGrjtzjwEnNEZZEdmBMYYPmvf97oxuSBqpUAuLi3Cf3RzVb8RrOEgZq2nYtWTbv4fuSPVPbDdl2CvDMOA0scNeLp4bXgiUJ1j16/4FTs0SzJ5Y658sJy9VA7sxs+upTAVuxJ7KljAFTbPspK+rpCZOHcf10LFFZdKeOkEqbT3+SWrAP0J2INsbmS51UBvWvWLXC5U7vaFcmJUpgpr58oIP05tcyHL0JRKPztiDXQ7qVlCk
    SECRET: AgBAsiCE+B8menHxJkKDZpW0dwxVGEAcruCRj5zhcJrtKLxitKocPlkFxxWrh9eErwmYjKoa1/BQ5+maDx7kplL4F2KPe6RkdxyErUbBIUUcVg5MLS7dreaJBYhDvpushn9/DTRIVLyEY80ejiKMX5vBUFBKS3SBRXeNl05LCuZyg/5sylJ57vJLxJSxbjAHud6SN8+cC8HbEdkwxIwpjvhH4WIUnEQPaY9Qo58g7thuNV/zXcUWLtWj2Twrat7+SR16xGwyeol02a/IUCJiEFapSGAW0QBrzf2gYzx1FWbG4Y+bl+ofYgMxSlf7aO0C2mOJG+22yYjVFk/SLDmcZtZ03hWG/Bojsk8fTYoLnQOY2ZwitWVVVeJOVNI03824vwqHCCMeTThY91tmZY0T92L7CbJiKi72R4f4d1e3hE0PFVSYmXOeGyFqk1TEq9E196BB5FiOFVxH2rwoTmjGahYEhE5VndQKUUqsTr/ZJvNXvhf3CZnNBF7g9KiB7y7ec4+Ah/Ns9mGClnUBxqU6UhrlAty+TnPii0vE6P1+hX5ee+S7uMWCc0IXddCIu1wOoDkUbVENRptce87H32Y8s05a2yTVRouBsClImfNZHRPRj5XqBeTGJKqOHTn7guvKtWlemouHfo3sZ7M2CSOA45LdpwUKs0py6WDr4qXq5EUhm+PAhtQl0zMRWORpMqnvR2AyguTVvZ/TstgRzn9CHPNXRyv6JB1Xc1O4n4S70yGz6hDcfE0ZCyqKtaRdPHHU1t49pZ7nryB3up4nyeLd0X2T
  template:
    metadata:
      name: traefik-forward-auth-secrets
      namespace: default
    type: Opaque
