ports:
  web:
    port: 80
    nodePort: 32513
    exposedPort: 80
    protocol: TCP

  websecure:
    port: 443
    nodePort: 32392
    exposedPort: 443
    protocol: TCP

service:
  type: NodePort

ingressClass:
  enabled: true
  isDefaultClass: true
  name: traefik

providers:
  kubernetesIngress:
    enabled: true
    ingressClass: traefik
    publishedService:
      enabled: true
      path: "traefik/traefik"
  kubernetesCRD:
    enabled: true

